apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: v2.15.1
    releaseName: sealed-secrets
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
