apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - image: nginxinc/nginx-unprivileged
          name: test
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 101
